In [1]:
import torch
from torch.distributions import multinomial

In [14]:
fair_probs = torch.ones([6]) / 6
# 进行 500 组实验，每组进行 10 次抽样
counts = multinomial.Multinomial(10, fair_probs).sample((500,))

print(counts.size())
print(counts)

# dim = 0，按行将数据累加；dim = 1，按列将数据累加
cum_counts = counts.cumsum(dim=0)
print(cum_counts)

# print(cum_counts.sum(dim=1, keepdim=True).size())
# print(cum_counts.sum(dim=1).size())
# 按行或者按列求和， keepdims 保证结果保持原矩阵的维度
print(cum_counts.sum(dim=0, keepdim=True))
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)

# d2l.set_figsize((6, 4.5))
# for i in range(6):
#     d2l.plt.plot(estimates[:, i].numpy(),
#                  label=("P(die=" + str(i + 1) + ")"))
# d2l.plt.axhline(y=0.167, color='black', linestyle='dashed')
# d2l.plt.gca().set_xlabel('Groups of experiments')
# d2l.plt.gca().set_ylabel('Estimated probability')
# d2l.plt.legend();

torch.Size([500, 6])
tensor([[3., 3., 0., 2., 0., 2.],
        [1., 1., 1., 3., 2., 2.],
        [4., 2., 2., 1., 1., 0.],
        ...,
        [1., 0., 0., 2., 5., 2.],
        [1., 2., 3., 0., 2., 2.],
        [1., 1., 1., 2., 1., 4.]])
tensor([[  3.,   3.,   0.,   2.,   0.,   2.],
        [  4.,   4.,   1.,   5.,   2.,   4.],
        [  8.,   6.,   3.,   6.,   3.,   4.],
        ...,
        [836., 824., 832., 854., 836., 798.],
        [837., 826., 835., 854., 838., 800.],
        [838., 827., 836., 856., 839., 804.]])
tensor([[212109., 209834., 206851., 217427., 205653., 200626.]])
