### 导包

In [10]:
import torch

### 标量自动微分

In [11]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = x**2+y
z.backward()
print(z, x.grad, y.grad)

tensor(3., grad_fn=<AddBackward0>) tensor(2.) tensor(1.)


### 向量自动微分

In [27]:

x = torch.rand(3, requires_grad=True)
print(x)

y = x**2
print(y)

z = x + x
print(z)

# 只有标量可以调用 backward
y.sum().backward()
print(y, x.grad)

# 为了防止梯度累加，将之前的梯度清零
x.grad.zero_()

# 以下四种方式等同
# z.sum().backward()
# z.backward(torch.ones(len(x)))
# torch.autograd.backward(z, torch.ones(len(x)))
grads = torch.autograd.grad(z, x, torch.ones(len(x)))
print(z, grads)

tensor([0.7836, 0.1262, 0.1162], requires_grad=True)
tensor([0.6140, 0.0159, 0.0135], grad_fn=<PowBackward0>)
tensor([1.5671, 0.2525, 0.2323], grad_fn=<AddBackward0>)
tensor([0.6140, 0.0159, 0.0135], grad_fn=<PowBackward0>) tensor([1.5671, 0.2525, 0.2323])
tensor([1.5671, 0.2525, 0.2323], grad_fn=<AddBackward0>) (tensor([2., 2., 2.]),)
