### 导包

In [12]:
import torch

### 测试函数

#### tensor

In [13]:
# 创建指定 size 的张量，数据为随机值
ts = torch.Tensor(3, 4)
print(ts)

# 根据列表创建张量，数据类型默认为 float
a_tensor = torch.Tensor([1, 2, 3, 4])
print(a_tensor)

# 创建 int 型的张量
b_tensor = torch.IntTensor([1, 2, 3, 4])
print(b_tensor)

# 以张量创建张量，共享 data
c_tensor = torch.IntTensor(b_tensor)
b_tensor += 1
print(b_tensor, c_tensor)       # tensor([2, 3, 4, 5], dtype=torch.int32) tensor([2, 3, 4, 5], dtype=torch.int32)

# 可用 python 列表，numpy 数组，Tensor 张量创建，不可以通过指定大小创建
# 这是一个 torch 的方法，上边的 Tensor 是一个类
ts1_n = [1, 2, 3, 4]
ts1 = torch.tensor(ts1_n)
print(ts1)

# tensor() 方法不共享data内存，用 is 和 id 判断都不准，tensor() 方法总是对 data 进行一份拷贝
a = [1, 2, 3, 4]
d_tensor = torch.tensor(a)
e_tensor = torch.tensor(d_tensor)
d_tensor += 1
print(a, d_tensor, e_tensor)        # [1, 2, 3, 4] tensor([2, 3, 4, 5]) tensor([1, 2, 3, 4])
# print(id(d_tensor.storage), id(e_tensor.storage))


tensor([[1.4249e-38, 3.0850e-41, 1.4427e-38, 3.0850e-41],
        [8.9683e-44, 0.0000e+00, 1.1210e-43, 0.0000e+00],
        [1.4280e-38, 3.0850e-41, 0.0000e+00, 0.0000e+00]])
tensor([1., 2., 3., 4.])
tensor([1, 2, 3, 4], dtype=torch.int32)
tensor([2, 3, 4, 5], dtype=torch.int32) tensor([2, 3, 4, 5], dtype=torch.int32)
tensor([1, 2, 3, 4])
[1, 2, 3, 4] tensor([2, 3, 4, 5]) tensor([1, 2, 3, 4])


/tmp/ipykernel_339937/4077079391.py:27: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  e_tensor = torch.tensor(d_tensor)


In [25]:
# 从均匀分布返回一个随机数填充的张量，区间为[0, 1)
tr = torch.rand(2, 3)
print(tr)

# 从标准正态分布返回一个随机填充的张量，均值为 0，方差为 1
trn = torch.randn(2, 3)
print(trn)

# 返回一个全为 1 的张量
t_one = torch.ones(2, 3)
t_zero = torch.zeros(2, 3)
# 返回一个与输入张量形状一样的张量
t_one_1 = torch.ones_like(t_one)
t_zero_1 = torch.zeros_like(t_zero)
print(t_one)
print(t_one_1)
print(t_zero)
print(t_zero_1)

# 用 0 填充自己
t_one.zero_()
print(t_one)

# 改变当前张量的 size，返回的新的张量和当前张量共享 data
t_one_view = t_one.view(-1, 2)
print(t_one)
print(t_one_view)
t_one[0][1] = 1
print(t_one)
print(t_one_view)

# 矩阵乘法
data_1 = torch.ones(2, 3)
data_2 = torch.ones(3, 2)
data = torch.mm(data_1, data_2)
print(data)

# 返回张量所有元素的和
print(torch.sum(data))

# 计算点积
torch.dot()

tensor([[0.7363, 0.7736, 0.9905],
        [0.5889, 0.3096, 0.1179]])
tensor([[-0.6578,  0.9412,  1.1411],
        [-0.3230, -1.4090,  1.5763]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 1., 0.],
        [0., 0., 0.]])
tensor([[0., 1.],
        [0., 0.],
        [0., 0.]])
tensor([[3., 3.],
        [3., 3.]])
tensor(12.)


### 标量自动微分

In [22]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = x**2 + y

# 返回一个新的张量，将 y 从计算图上分离
u = y.detach()

z = x**2 + u
z.backward()
print(z, x.grad, u.grad)

tensor(3., grad_fn=<AddBackward0>) tensor(2.) None


### 向量自动微分

In [16]:

x = torch.rand(3, requires_grad=True)
print(x)

y = x**2
print(y)

z = x + x
print(z)

# 只有标量可以调用 backward
y.sum().backward()
print(y, x.grad)

# 为了防止梯度累加，将之前的梯度清零
x.grad.zero_()

# 以下四种方式等同
# z.sum().backward()
# z.backward(torch.ones(len(x)))
# torch.autograd.backward(z, torch.ones(len(x)))
grads = torch.autograd.grad(z, x, torch.ones(len(x)))
print(z, grads)

tensor([0.5332, 0.5752, 0.7980], requires_grad=True)
tensor([0.2843, 0.3308, 0.6368], grad_fn=<PowBackward0>)
tensor([1.0664, 1.1503, 1.5960], grad_fn=<AddBackward0>)
tensor([0.2843, 0.3308, 0.6368], grad_fn=<PowBackward0>) tensor([1.0664, 1.1503, 1.5960])
tensor([1.0664, 1.1503, 1.5960], grad_fn=<AddBackward0>) (tensor([2., 2., 2.]),)
